version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: fables
      POSTGRES_USER: fables_user
      POSTGRES_PASSWORD: fables_password
    ports:
      - "5433:5432"

  web:
    build: .
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1
      DATABASE_URL: postgres://fables_user:fables_password@db:5432/fables
    depends_on:
      - db

volumes:
  postgres_data: