services:
  web:
    image: ghcr.io/turizak/fables:${IMAGE_TAG:-latest}
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      # Mount source code but exclude virtual environments
      - .:/app
      - /app/.venv  # Exclude .venv from bind mount
      - /app/.uv    # Exclude .uv from bind mount
      - /app/__pycache__  # Exclude __pycache__ from bind mount
    ports:
      - "8000:8000"
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      VERBOSE_LOGGING: ${VERBOSE_LOGGING}
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: