# Generated by Django 5.2.3 on 2025-07-10 01:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("username", models.CharField(max_length=100)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "account",
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("index", models.AutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "account_uuid",
                    models.ForeignKey(
                        db_column="account_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.account",
                        to_field="uuid",
                    ),
                ),
            ],
            options={
                "db_table": "campaign",
            },
        ),
    ]
