# Generated by Django 5.2.3 on 2025-07-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
