name: Cleanup Old Package Versions

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Delete old package versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'fables'
          package-type: 'container'
          min-versions-to-keep: 10
          delete-only-untagged-versions: false
          ignore-versions: '^(latest|dev)$'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete untagged versions
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'fables'
          package-type: 'container'
          min-versions-to-keep: 0
          delete-only-untagged-versions: true
          token: ${{ secrets.GITHUB_TOKEN }}