name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ruff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        run: |
          pip install uv

      - name: Install dependencies from pyproject.toml with uv
        run: |
          uv sync

      - name: Run Ruff Check
        run: |
          uv run ruff check . --output-format=github

      - name: Run Ruff Format Check
        run: |
          uv run ruff format . --check
